module.exports={
  devServer:{
    overlay:{
      warnings:false,
      errors:false
    },
    proxy:{
      '/info':{
        target:'http://47.96.0.211:3000',
        changeOrigin:true,
        pathRewrite:{
          '^/info':''
        }
      }
    }
  }
}